apps/goods/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import IndexView, DetailView, ListView, GoodsSeachView

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/<int:goods_id>', DetailView.as_view(), name='detail'),
    path('list/<int:type_id>/<int:page_num>', ListView.as_view(), name='list'),
    path('search/', GoodsSeachView(), name='search'), # / 必需，完整 url = /search/?q=xx
]

myDailyFresh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('', include('goods.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/search/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-搜索结果{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
						<li><a href="{% url 'goods:list' type.id 1 %}?sort=default" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">{{ query }}</a>
		<span>></span>
		<a href="#">搜索结果</a>
	</div>

	<div class="main_wrap clearfix">
		<ul class="goods_type_list clearfix">
			{% for item in page %}
			<li>
				<a href="{% url 'goods:detail' item.object.id %}"><img src="{{ item.object.image.url }}"></a>
				<h4><a href="{% url 'goods:detail' item.object.id %}">{{ item.object.name }}</a></h4>
				<div class="operate">
					{% csrf_token %}
					<span class="prize">￥{{ item.object.price }}</span>
					<span class="unit">{{ item.object.unite }}</span>
					<a href="javascript:;" sku_id="{{ item.object.id }}" class="add_goods" title="加入购物车"></a>
				</div>
			</li>
			{% endfor %}
		</ul>

		<div class="pagenation">
			{% if page.has_previous %}
				<a href="{% url 'goods:search' %}?q={{ query }}&page={{ page.previous_page_number }}">&lt;上一页</a>
			{% endif %}
			{% for num in paginator.page_range %}
				<a href="{% url 'goods:search' %}?q={{ query }}&page={{ num }}" {% if num == page.number %} class="active" {% endif %}>{{ num }}</a>
			{% endfor %}
			{% if page.has_next %}
				<a href="{% url 'goods:search' %}?q={{ query }}&page={{ page.next_page_number }}">下一页></a>
			{% endif %}
		</div>
	</div>
{% endblock body %}

{% block bottomfiles %}
	<div class="add_jump"></div>

	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

		var $add_x = $('.add_goods').offset().top
		var $add_y = $('.add_goods').offset().left
		var $to_x = $('#show_count').offset().top
		var $to_y = $('#show_count').offset().left

		// 点击加入购物车
		$('.add_goods').click(function() {
			sku_id = $(this).attr('sku_id')
			csrf = $('input[name="csrfmiddlewaretoken"]').val()
			parameters = {
				"sku_id": sku_id,
				'count': 1,
				'csrfmiddlewaretoken': csrf,
			}

			$.post('/cart/add', parameters, function (data) {
				if (data.status == 0) {
					// 设置动画的样式
					$(".add_jump").css({
						'left':$add_y+80,
						'top':$add_x+10,
						'display':'block'
					})
					$(".add_jump").stop().animate({
						'left': $to_y+7,
						'top': $to_x+7
					},
					"fast",
					function() {
						$(".add_jump").fadeOut('fast', function() {
							$('#show_count').html(data.cart_count)
						});
					});
				} else {
					alert(data.errmsg)
				}
			})
		})
	</script>
{% endblock bottomfiles %}