apps/cart/urls.py
from django.urls import path
from .views import InfoView, UpdateView, DeleteView, AddView

app_name = 'cart'
urlpatterns = [
    path('', InfoView.as_view(), name='info'),
    path('update', UpdateView.as_view(), name='update'),
    path('delete', DeleteView.as_view(), name='delete'),
    path('add', AddView.as_view(), name='add'),
]

apps/goods/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import IndexView, DetailView, ListView, GoodsSeachView

app_name = 'goods'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/<int:goods_id>', DetailView.as_view(), name='detail'),
    path('list/<int:type_id>/<int:page_num>', ListView.as_view(), name='list'),
    path('search/', GoodsSeachView(), name='search'), # / 必需，完整 url = /search/?q=xx
]

apps/order/urls.py
from django.urls import path
from .views import PlaceView, CreateView, PayView, QueryView, CommentView

app_name = 'order'
urlpatterns = [
    path('place/', PlaceView.as_view(), name='place'),
    path('create/', CreateView.as_view(), name='create'),
    path('pay/', PayView.as_view(), name='pay'),
    path('query/', QueryView.as_view(), name='query'),
    path('comment/<int:order_id>/', CommentView.as_view(), name='comment')
]

apps/user/urls.py
from django.urls import path
from django.conf.urls import url
from .views import RegisterView, ActiveView, LoginView, LogoutView, InfoView, OrderView, AddressView, AddressChangeView

app_name = 'user'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    # path(r'active/(?P<token>.*)', ActiveView.as_view(), name='active'),
    url(r"^active/(?P<token>.*)/$", ActiveView.as_view(), name='active'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('info', InfoView.as_view(), name='info'),
    path('order/<int:page_num>/', OrderView.as_view(), name='order'),
    path('address', AddressView.as_view(), name='address'),
    path('addressChange', AddressChangeView.as_view(), name='addressChange'),
]

myDailyFresh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import xadmin

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('', include('goods.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django_redis import get_redis_connection
from goods.models import GoodsSKU

# Create your views here.
class InfoView(LoginRequiredMixin, View):
    def get(self, request):
        ''' 主页点击我的购物车，跳转到 cart.html 页面 '''
        user = request.user
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        cart_dict = conn.hgetall(cart_key)
        cart_count = conn.hlen(cart_key)

        skus = []
        total_count = 0
        total_price = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            cnt = int(count)
            amount = sku.price * cnt
            sku.amount = amount
            sku.count = cnt
            skus.append(sku)

            total_count += cnt
            total_price += amount

        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus,
            'cart_count': cart_count,
        }
        return render(request, 'cart.html', context)


class UpdateView(View):
    def post(self, request):
        ''' 更新购物车信息 '''
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'status':1, 'errmsg':'请先登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        sku = GoodsSKU.objects.get(id=sku_id)
        count = int(count)
        if count > sku.stock:
            return JsonResponse({'status':2, 'errmsg':'库存不够'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        conn.hset(cart_key, sku_id, count)

        return JsonResponse({'status':0, 'count':count})


class DeleteView(View):
    def post(self, request):
        ''' 删除购物车信息 '''
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'status':1, 'errmsg':'请先登录'})

        sku_id = request.POST.get('sku_id')

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        conn.hdel(cart_key, sku_id)

        return JsonResponse({'status':0})


class AddView(View):
    def post(self, request):
        ''' 添加购物车信息 '''
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'status':1, 'errmsg':'请先登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        sku = GoodsSKU.objects.get(id=sku_id)
        count = int(count)

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        old_count = conn.hget(cart_key, sku_id)
        if old_count: # 之前有添加过该 sku_id
            count += int(old_count)
        if count > sku.stock:
            return JsonResponse({'status':2, 'errmsg':'库存不够'})

        conn.hset(cart_key, sku_id, count)
        cart_count = conn.hlen(cart_key)
        return JsonResponse({'status':0, 'cart_count':cart_count})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load static %}

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block topfiles %}
	{% endblock topfiles %}
</head>

<body>
	{% block header_con %}
		<div class="header_con">
			<div class="header">
				<div class="welcome fl">欢迎来到天天生鲜</div>
				<div class="fr">
					{% if user.is_authenticated %}
						<div class="login_btn fl">
							欢迎您：<em>{{ user.username }}</em>
							<span>|</span>
							<a href="{% url 'user:logout' %}">退出登录</a>
						</div>
					{% else %}
						<div class="login_btn fl">
							<a href="{% url 'user:login' %}">登录</a>
							<span>|</span>
							<a href="{% url 'user:register' %}">注册</a>
						</div>
					{% endif %}

					<div class="user_link fl">
						<span>|</span>
						<a href="{% url 'user:info' %}">用户中心</a>
						<span>|</span>
						<a href="{% url 'cart:info' %}">我的购物车</a>
						<span>|</span>
						<a href="{% url 'user:order' 1 %}">我的订单</a>
					</div>
				</div>
			</div>		
		</div>
	{% endblock header_con  %}

	{% block search_bar %}
		<div class="search_bar clearfix">
			<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
			<div class="search_con fl">
				<form action="{% url 'goods:search' %}" method="get">
					<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
					<input type="submit" class="input_btn fr" name="" value="搜索">
				</form>
			</div>
			<div class="guest_cart fr">
				<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
				<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
			</div>
		</div>
	{% endblock search_bar %}

	{% block body %}
	{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	{% block bottom %}
	{% endblock bottom %}

	{% block bottomfiles %}
	{% endblock bottomfiles %}
</body>

</html>

templates/base_user_center.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-用户中心{% endblock title %}
{% block topfiles %}{% endblock topfiles %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock search_bar %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}" {% if page_type == 'info' %} class="active" {% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page_type == 'order' %} class="active" {% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page_type == 'address' %} class="active" {% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		{% block right_content %}
		{% endblock right_content %}
	</div>
{% endblock body %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-购物车{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

{% block body %}
    <ul class="cart_list_th clearfix">
        <li class="col01">商品名称</li>
        <li class="col02">商品单位</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">小计</li>
        <li class="col06">操作</li>
    </ul>

    <form action="{% url 'order:place' %}" method="post">
    {% csrf_token %}
    {% for sku in skus %}
        <ul class="cart_list_td clearfix">
            <li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
            <li class="col02"><img src="{{ sku.image.url }}"></li>
            <li class="col03">{{ sku.name }}<br><em>{{ sku.price }}/{{ sku.unite }}</em></li>
            <li class="col04">{{ sku.unite }}</li>
            <li class="col05">{{ sku.price }}</li>
            <li class="col06">
                <div class="num_add">
                    {% csrf_token %}
                    <a href="javascript:;" class="add fl">+</a>
                    <input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
                    <a href="javascript:;" class="minus fl">-</a>
                </div>
            </li>
            <li class="col07">{{ sku.amount }}</li>
            <li class="col08"><a href="javascript:;" class="delete">删除</a></li>
        </ul>
    {% endfor %}

        <ul class="settlements">
            {% csrf_token %}
            <li class="col01"><input type="checkbox" name="select_all" checked></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
            <li class="col04"><input type="submit" value="去结算"></li>
        </ul>
    </form>
{% endblock body %}

{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        // 全选 checkbox 按钮变化
        $(".settlements").find(':checkbox').change(function () {
            is_checked = $(this).prop('checked') // 获取全选的选中状态
            $('.cart_list_td').find(':checkbox').each(function () { // 遍历所有商品的选中状态，设置为 is_checked 状态
                $(this).prop('checked', is_checked)
            })
            update_page_info() // 更新某一商品小计，商品总数量和总价格
        })

        // 单个商品 checkbox 按钮变化
        $('.cart_list_td').find(":checkbox").change(function () {
            all_len = $(".cart_list_td").length // 获取页面所有商品数目
            checked_len = $('.cart_list_td').find(':checked').length // 获取页面上被选中的商品数目
            $(".settlements").find(':checkbox').prop('checked', all_len == checked_len) // 设置全选 checkbox 按钮状态
            update_page_info()
        })

        // 点击 + 按钮
        $('.add').click(function () {
            sku_id = $(this).next().attr('sku_id')
            count = parseInt($(this).next().val()) + 1
            send_ajax_update(sku_id, count)
        })

        // 点击 - 按钮
        $('.minus').click(function () {
            sku_id = $(this).prev().attr('sku_id')
            count = parseInt($(this).prev().val()) - 1
            if (count > 0) {
                send_ajax_update(sku_id, count)
            }
        })

        // 手动修改数量
        pre_count = 0
        $('.num_show').focus(function () { // input 输入框获得焦点
            pre_count = $(this).val() // 保存原来的值
        })

        $('.num_show').blur(function() { // input 输入框失去焦点
            count = $(this).val() // 获取新的值
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0) {
                $(this).val(pre_count)
                return
            }

            sku_id = $(this).attr('sku_id')
            count = parseInt(count)
            send_ajax_update(sku_id, count)
        })

        // 点击删除按钮
        $('.delete').click(function() {
            ul = $(this).parents('.cart_list_td') // 获取商品所在的 ul 元素
            sku_id = ul.find('.num_show').attr('sku_id')
            send_ajax_delete(sku_id, ul)
        })

        // 更新某一商品小计，商品总数量和总价格
        function update_page_info() {
            total_count = 0
            total_price = 0
            $(".cart_list_td").find(":checked").parents('ul').each(function () {
                count = parseInt($(this).find('.num_show').val())
                price = parseFloat($(this).find('.col05').text())
                amount = price * count
                $(this).children('.col07').text(amount.toFixed(2)) // 更新某一商品小计

                total_count += count
                total_price += amount
            })
            $('.settlements').find('em').text(total_price.toFixed(2)) // 更新商品总数量和总价格
            $('.settlements').find('b').text(total_count)
        }

        // 发送 ajax 请求，更新购物车某一 sku_id 数据信息
        function send_ajax_update(sku_id, count) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            parameter = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrf
            }
            // $.ajaxSettings.async = false
            $.post('/cart/update', parameter, function(data) {
                if (data.status == 0) { // 回调函数，数据库更新成功
                    $('input[sku_id=' + parameter.sku_id + ']').val(data.count) // 更新某一商品数量
                    update_page_info()
                } else {
                    alert(data.errmsg)
                }
            })
        }

        // 发送 ajax 请求，删除购物车某一 sku_id 数据信息
        function send_ajax_delete(sku_id, ul) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            parameter = {
                'sku_id': sku_id,
                'csrfmiddlewaretoken': csrf
            }
            // $.ajaxSettings.async = false
            $.post('/cart/delete', parameter, function(data) {
                if (data.status == 0) { // 回调函数，数据库更新成功
                    is_checked = ul.find(':checkbox').prop('checked')
                    ul.remove()
                    if (is_checked) { // 删除的商品没有被选中，则不影响商品总数量和总价格
                        update_page_info()
                    }
                } else {
                    alert(data.errmsg)
                }
            })
        }
    </script>
{% endblock bottomfiles %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-登录{% endblock title %}

{# clear unused block #}
{% block topfiles %}{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}

{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static "images/logo02.png" %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{% url 'user:login' %}">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名或邮箱" value="{{ login_form.username.value }}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码"">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
				<div style="text-align: center; background-color: red; color: white;">
					{% for key,error in login_form.errors.items %}
						{{ error }}
					{% endfor %}
					{{ errmsg }}
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/order_comment.html
{% extends 'base_user_center.html' %}
{% load static %}

{% block right_content %}
    <div class="right_content clearfix">
    <h3 class="common_title2">订单评价</h3>
    <ul class="order_list_th w978 clearfix">
        <li class="col01">{{ order.create_time }}</li>
        <li class="col02">订单号：{{ order.order_id }}</li>
        <li class="col02 stress">{{ order.status_name }}</li>
    </ul>

    <form action="{% url 'order:comment' order.order_id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="order_id" value="{{ order.order_id }}">
        {# 订单有多少个商品 #}
        <input type="hidden" name="total_count" value="{{ order.order_goods_list|length }}">

        {% for order_goods in order.order_goods_list %}
        <table class="order_list_table w980">
            <tbody>
            <tr>
                <td width="80%">
                    <ul class="order_goods_list clearfix">
                        <li class="col01"><img src="{{ order_goods.sku.image.url }}"></li>
                        <li class="col02">{{ order_goods.sku.name }}<em>单价:{{ order_goods.sku.price }}/{{ order_goods.sku.unite }}</em></li>
                        <li class="col03">购买数量: {{ order_goods.count }}</li>
                    </ul>
                </td>
                <td width="20%">小计: {{ order_goods.amount }}元</td>
            </tr>
            </tbody>
        </table>
        <div class="site_con">
            <input type="hidden" name="sku_{{ forloop.counter }}" value="{{ order_goods.sku.id }}">
            <div class="form_group form_group2">
                <label>评价内容：</label>
                <textarea class="site_area" name="content_{{ forloop.counter }}"></textarea>
            </div>
        </div>
        {% endfor %}

        <input type="submit" name="" value="提交" class="info_submit">
    </form>

</div>
{% endblock right_content %}

templates/order_place.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-提交订单{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

{% block body %}
	<h3 class="common_title">确认收货地址</h3>
	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			{% for addr in addrs %}
				<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %} checked {% endif %}>{{ addr.addr }} ({{ addr.receiver }} 收) {{ addr.phone }}</dd>
			{% endfor %}
		</dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>
	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}</li>
		</ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>
	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}</b></div>
			<div class="transit">运费：<b>{{ transit_price }}</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		{% csrf_token %}
		<a href="javascript:;" sku_ids="{{ sku_ids }}" id="order_btn">提交订单</a>
	</div>	
{% endblock body %}

{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功</p>
		</div>
		<div class="mask"></div>
	</div>
{% endblock bottom %}

{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
    $("#order_btn").click(function () {
        addr_id = $('input[name="addr_id"]:checked').val()
        pay_method = $('input[name="pay_style"]:checked').val()
        sku_ids = $(this).attr("sku_ids")
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params = {
			'addr_id': addr_id,
			"pay_method": pay_method,
			'sku_ids': sku_ids,
        	'csrfmiddlewaretoken':csrf,
        }
        $.post('/order/create/', params, function (data) {
            if (data.status == 0) {
            	localStorage.setItem('order_finish', 2)
				$('.popup_con').fadeIn('fast', function() {
					setTimeout(function() {
						$('.popup_con').fadeOut('fast', function() {
							window.location.href = "{% url 'user:order' 1 %}"
						})
					}, 3000)
				})
			} else {
				alert(data.errmsg)
			}
		})
	})
	</script>
{% endblock bottomfiles %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}

{# clear unused block #}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="{% url 'goods:index' %}"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">
					{% csrf_token %}
					<ul>
						<li>
							<label>用户名:</label>
							<input type="text" name="user_name" id="user_name">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>密码:</label>
							<input type="password" name="pwd" id="pwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>确认密码:</label>
							<input type="password" name="cpwd" id="cpwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>邮箱:</label>
							<input type="text" name="email" id="email">
							<span class="error_tip">提示信息</span>
						</li>
						<li class="agreement">
							<input type="checkbox" name="allow" id="allow" checked="checked">
							<label>同意”天天生鲜用户使用协议“</label>
							<span class="error_tip2">提示信息</span>
						</li>
						<li class="reg_sub">
							<input type="submit" value="注 册" name="">
						</li>
					</ul>
				</form>
				{{ errmsg }}
			</div>
		</div>
	</div>
{% endblock body%}